Testing the GPU golden images

diff --git a/integration_test/third_party_apps_test/applications/dcgm/debian_ubuntu/install b/integration_test/third_party_apps_test/applications/dcgm/debian_ubuntu/install
--- a/integration_test/third_party_apps_test/applications/dcgm/debian_ubuntu/install
+++ b/integration_test/third_party_apps_test/applications/dcgm/debian_ubuntu/install
@@ -1,50 +1,22 @@
 set -e
 source /etc/os-release
-
-sudo apt update
-KERNEL_VERSION=`uname -r`
-sudo apt install -y linux-headers-${KERNEL_VERSION} software-properties-common pciutils gcc make dkms wget
-
-# Install CUDA and driver the same way as the nvml app
-# Prefer to install from the package manager since it is normally faster and has
-# less errors on installation; fallback to the runfile method if the package
-# manager's package is not working or not compitible with the GPU model
 DISTRIBUTION=$(echo $ID$VERSION_ID | sed -e 's/\.//g')
-# Need to add the keyring for installing CUDA and DCGM
-wget --no-verbose https://developer.download.nvidia.com/compute/cuda/repos/${DISTRIBUTION}/x86_64/cuda-keyring_1.1-1_all.deb
-sudo dpkg -i cuda-keyring_1.1-1_all.deb
-echo "Installing latest version of NVIDIA CUDA and driver"
-if [[ $ID == debian ]]; then
-    sudo add-apt-repository contrib
+
+# Fix for broken Bullseye Backports (prevents apt update failure)
+if [[ "$DISTRIBUTION" == "debian11" ]]; then 
+    if grep -q "bullseye-backports" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
+        sudo sed -i '/bullseye-backports/s/^/#/' /etc/apt/sources.list
+        sudo sed -i '/bullseye-backports/s/^/#/' /etc/apt/sources.list.d/*.list
+    fi
 fi
-sudo apt update
 
-DEVICE_CODE=$(lspci -n | grep -Po '10de:[\w\d]{4}')
-case $DEVICE_CODE in
-    # V100 | P4 | P100
-    # Device PCIe ID lookup: https://envytools.readthedocs.io/en/latest/hw/pciid.html
-    10de:1db1|10de:1bb3|10de:15f8)
-        # For GPUs older than Turing (Volta: V100, Pascal: P4, P100):
-        # 1. R580 is the last driver branch to support the Pascal (P4 and P100) and Volta architecture (V100).
-        # https://docs.cloud.google.com/compute/docs/gpus/install-drivers-gpu#recommended-driver-branches
-        # 2. They need proprietary kernel modules, not the open kernel modules (nvidia-open-*)
-        sudo apt -y install nvidia-driver-575
-        sudo apt -y install cuda-12-9
-        ;;
-    *)
-        # For newer GPUs, install the latest version
-        if [[ $ID == debian && "${VERSION_ID}" == 11 ]]; then
-            # cuda-12-6 is the latest version that supports Debian 11
-            sudo apt -y install cuda-12-6
-        else
-            sudo apt -y install nvidia-driver-575
-            sudo apt -y install cuda-12-9
-        fi
-        ;;
-esac
-
-# check NVIDIA driver installation succeeded
-nvidia-smi
+if ! dpkg -s cuda-keyring >/dev/null 2>&1; then
+    filename="cuda-keyring_1.1-1_all.deb"
+    url="https://developer.download.nvidia.com/compute/cuda/repos/${DISTRIBUTION}/x86_64/${filename}"
+    
+    wget --no-verbose "$url"
+    sudo dpkg -i "$filename"
+fi
 
 # Install DCGM
 sudo apt-get update
